[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "foundry-devops/=lib/foundry-devops/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
